Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,6 +42,14 @@ jobs:
             echo "File format not supported or recognized."
             exit 1
 
+      - name: Verify extracted file
+        run: |
+          echo "Checking if extracted image exists..."
+          if [[ ! -f "download/$img_file" ]]; then
+            echo "Error: Extracted image not found!"
+            exit 1
+          fi
+
       - name: Build
         run: |
           cp ./build.sh download
